[build]
builder = "dockerfile"
dockerfilePath = "packages/server/Dockerfile"

[deploy]
startCommand = "npm run start -w @paddlelink/server"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
